#!/usr/bin/env python3
"""
Find features that are simultaneously driving both FAR and FRR
for each user and globally.
Reads the per‑user CSV files generated by analyze_FAR_FRR.py.

Usage: python common_features.py [top_n]
"""

import os, sys, warnings
import pandas as pd
import numpy as np

warnings.filterwarnings("ignore")

# ======================= CONFIGURATION =======================
USER_LIST = [
    "reddy56", "Nikitha18", "Diana", "Avnish", "skyy",
    "Pranav", "surya", "divya", "Saurabh", "srikanth",
    "Samarth", "harshit"
]
# =============================================================

def main():
    if len(sys.argv) > 1:
        try:
            TOP_N = int(sys.argv[1])
        except ValueError:
            print("Invalid top_n. Using 20")
            TOP_N = 20
    else:
        TOP_N = 20
    print(f"Using top‑{TOP_N} features from each side\n")

    global_common_counts = {}   # feature -> number of users where it appears in both top‑N

    for user in USER_LIST:
        far_file = f"FAR_features_{user}.csv"
        frr_file = f"FRR_features_{user}.csv"

        if not os.path.exists(far_file) or not os.path.exists(frr_file):
            print(f"  Missing files for {user}, skipping.")
            continue

        far_df = pd.read_csv(far_file)
        frr_df = pd.read_csv(frr_file)

        # Take top‑N features (first N rows) from each list
        far_top = set(far_df.head(TOP_N)["feature"])
        frr_top = set(frr_df.head(TOP_N)["feature"])

        common = far_top & frr_top
        if common:
            # Create a combined DataFrame for the user
            # We'll include the rankings from both sides
            far_ranked = far_df[far_df["feature"].isin(common)][["feature", "z_diff_FAR", "rank_FAR"]]
            frr_ranked = frr_df[frr_df["feature"].isin(common)][["feature", "z_diff_FRR", "rank_FRR"]]
            common_df = far_ranked.merge(frr_ranked, on="feature", how="inner")
            common_df = common_df.sort_values(["rank_FAR", "rank_FRR"])
            common_df.to_csv(f"common_features_{user}.csv", index=False)
            print(f"[{user}] common features: {len(common)}")

            for feat in common:
                global_common_counts[feat] = global_common_counts.get(feat, 0) + 1
        else:
            print(f"[{user}] No common features found in top‑{TOP_N}")

    # Global summary
    if global_common_counts:
        global_common_df = pd.DataFrame({
            "feature": list(global_common_counts.keys()),
            "common_user_count": list(global_common_counts.values())
        }).sort_values("common_user_count", ascending=False)
        global_common_df.to_csv("common_features_global.csv", index=False)

        print("\n=== FEATURES MOST OFTEN IN BOTH FAR AND FRR TOP‑LISTS (global) ===")
        print(global_common_df.head(20).to_string(index=False))
        print("\nGlobal common file: common_features_global.csv")
    else:
        print("\nNo common features found across any user.")


if __name__ == "__main__":
    main()
